# <center>LAB 2 - Completing Pandas

---------------------------

Name: **KRISH GOYAL** <br>
Reg No: **21112015** <br>
Class: **3 BSC DS** <br>

---------------
    
    
<u>**Objectives**</u>  
- Import the TITANIC Dataset 
- Print the Head and Tail of the Dataset 
- Change Titles of at least 3 different attributes (For Eg, change Survived --> Survival_Status)
- The Fare, which is mentioned in USD, convert to INR based on the current exchange rate
- Making the use of the iterrows() method

-----------------
    
<u>**Problem Statement**</u>  
- Importing Dataset from the Link and then change column names and converting fares to INR.
- Making the analysis and gaining insights from the Dataset and finding the descriptive statistics of the dataset.

-------------------
    
<u>**Methods**</u> 
- Loading Dataset using **pd.read_csv()**
- Renaming the **Survived** , **fare** and **Sex** Columns
- Maping Survived Column with the Survived and Not Survived using **map()** function
- Cross tabulation of the data using  **pd.crosstab()** function
- Creating new columns such as **Prices_Inr* &	**Passenger_Income** &	**Age_class**
- Using The **iterrows()** method     
- Finding descriptive statistics using **describe()** function in pandas library
- Counting the Each categories of Flowers present using **value_counts()**
- Extracting the values of Sepal_length and Petal_Width using greater than operater**(>)**
- Extracting the values which are higher in sum column from the input given by user using greater than operator**(>)**

------------------
    
<u>**Observations**</u>
- Successfully imported the dataset
- Returns the first five values through head() and last five values through tail() in the dataset
- Renaming the columns of Survived , Fare and Sex.
- Converting teh Prices from USD to INR and craeting a new Column
- Total number of entries are 887 and Survival_status, Pclass, Siblings/Spouses Aboard,Parents/Children Aboard are interger datatype <br>Age , Fare Paid are float datatype <br>Name and Gender are object datatype
- Descriptive Statistics shows the count, mean, standard deviation, min, max, 25%, 50%,75% of each column of the dataset which helps us to gain meaningful insights
- The number of Males and Females are 573 and 314 respectively.
- There are no null values in the dataset as the values are zero
- Memory Usage by the various datypes in bytes
- The Number of Survived and not Survived People are 545 and 342 Respectively.
- The numbers of Passengers who travelled for free are 15
- The Income of Passengers were categorised based on two factors Below and Above Average    
- The number of Males and females who survived and not survived    
- The Male Passengers who survived in Class1 are 45
- The Male Passengers who survived in Class2 are 17
- The Male Passengers who survived in Class3 are 47
- The People are categorised based on Adult,Child and Senior Citizen respectively.
- Droped the Fare_Paid column from the dataset
- The number of Lower_Class ,Middle_class & Upper_class Survived and Not Survived , i.e. ,categorisation based upon classes 
- The number of Married and unmarried Peoples
    
------------------
 
<u>**Results**</u>
- There are 690 Adults and 130Children and 67 Senior Citizen in the dataset
- There are 545 males and 342 females who survied are present in the dataset 

------------------
 
<u>**Learnings & Reflection**</u>
- Importing the Dataset using Link
- Creating Columns for Prices_INR , Age Category , Income and Married Status
- Getting better insights about the TITANIC Dataset that what are the Males who survived in Pclass 1,2,3
- Usage of  mean , and map Functions
    
------------------

<u>**References**</u> <br>
1. [DataCamp](https://www.datacamp.com/cheat-sheet/pandas-cheat-sheet-for-data-science-in-python)<br> 
2. [Pandas Documendation](https://pandas.pydata.org/)<br>
3. [Pandas Functions](https://regenerativetoday.com/30-very-useful-pandas-functions-for-everyday-data-analysis-tasks)<br>
------------------

<u><center>**Completion Status**</u>

| Question Number | Status |
| --- | --- |
| 1 | Completed |
| 2 | Completed |
| 3 | Completed |
| 4 | Completed |
| 5 | Completed |
| 6 | Completed |
| 7 | Completed |
| 8 | Completed |

In [1]:
import pandas as pd
from statistics import mean
# load dataset
df = pd.read_csv("D:/COLLEGE DATA/SEM III/BDS371L - Data Analytics Lab/titanic.csv")
df

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      male  22.0                        1                        0   7.2500  
1    female  38.0                        1                        0  71.2833  
2    female  26.0                        0                        0   7.9250  
3    female  35.0                        1                        0  53.1000  
4      male  35.0                        0                        0   8.0500  
..      ...   ...                      ...                      ...      ...  
882    male  27.0                        0                        0  13.0000  
883  female  19.0                        0                        0  30.0000  
884  female   7.0                        1                        2  23.4500  
885    male  26.0                        0                        0  30.0000  
886    male  32.0                        0                        0   7.7500  

[887 rows x 8 columns]

**Observation** - *Successfully imported the dataset*

In [2]:
df.head()

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0    male  22.0                        1                        0   7.2500  
1  female  38.0                        1                        0  71.2833  
2  female  26.0                        0                        0   7.9250  
3  female  35.0                        1                        0  53.1000  
4    male  35.0                        0                        0   8.0500

In [3]:
df.tail()

Survived  Pclass                            Name     Sex   Age  \
882         0       2            Rev. Juozas Montvila    male  27.0   
883         1       1     Miss. Margaret Edith Graham  female  19.0   
884         0       3  Miss. Catherine Helen Johnston  female   7.0   
885         1       1            Mr. Karl Howell Behr    male  26.0   
886         0       3              Mr. Patrick Dooley    male  32.0   

     Siblings/Spouses Aboard  Parents/Children Aboard   Fare  
882                        0                        0  13.00  
883                        0                        0  30.00  
884                        1                        2  23.45  
885                        0                        0  30.00  
886                        0                        0   7.75

**Observation** - *Returns the first five values through head() and last five values through tail() in the dataset*

In [4]:
df.rename(columns= {'Survived':'Survival_Status','Sex':'Gender','Fare':'Fare_Paid'},inplace = True)
df

Survival_Status  Pclass  \
0                  0       3   
1                  1       1   
2                  1       3   
3                  1       1   
4                  0       3   
..               ...     ...   
882                0       2   
883                1       1   
884                0       3   
885                1       1   
886                0       3   

                                                  Name  Gender   Age  \
0                               Mr. Owen Harris Braund    male  22.0   
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  38.0   
2                                Miss. Laina Heikkinen  female  26.0   
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  female  35.0   
4                              Mr. William Henry Allen    male  35.0   
..                                                 ...     ...   ...   
882                               Rev. Juozas Montvila    male  27.0   
883                        Miss. Margaret Edith Graham  female  19.0   
884                     Miss. Catherine Helen Johnston  female   7.0   
885                               Mr. Karl Howell Behr    male  26.0   
886                                 Mr. Patrick Dooley    male  32.0   

     Siblings/Spouses Aboard  Parents/Children Aboard  Fare_Paid  
0                          1                        0     7.2500  
1                          1                        0    71.2833  
2                          0                        0     7.9250  
3                          1                        0    53.1000  
4                          0                        0     8.0500  
..                       ...                      ...        ...  
882                        0                        0    13.0000  
883                        0                        0    30.0000  
884                        1                        2    23.4500  
885                        0                        0    30.0000  
886                        0                        0     7.7500  

[887 rows x 8 columns]

**Observation** - *Renaming the columns of Survived , Fare and Sex.*

In [5]:
df['Prices_Inr'] = (df['Fare_Paid'] * 79.5875).round(decimals= 2)
df

Survival_Status  Pclass  \
0                  0       3   
1                  1       1   
2                  1       3   
3                  1       1   
4                  0       3   
..               ...     ...   
882                0       2   
883                1       1   
884                0       3   
885                1       1   
886                0       3   

                                                  Name  Gender   Age  \
0                               Mr. Owen Harris Braund    male  22.0   
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  38.0   
2                                Miss. Laina Heikkinen  female  26.0   
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  female  35.0   
4                              Mr. William Henry Allen    male  35.0   
..                                                 ...     ...   ...   
882                               Rev. Juozas Montvila    male  27.0   
883                        Miss. Margaret Edith Graham  female  19.0   
884                     Miss. Catherine Helen Johnston  female   7.0   
885                               Mr. Karl Howell Behr    male  26.0   
886                                 Mr. Patrick Dooley    male  32.0   

     Siblings/Spouses Aboard  Parents/Children Aboard  Fare_Paid  Prices_Inr  
0                          1                        0     7.2500      577.01  
1                          1                        0    71.2833     5673.26  
2                          0                        0     7.9250      630.73  
3                          1                        0    53.1000     4226.10  
4                          0                        0     8.0500      640.68  
..                       ...                      ...        ...         ...  
882                        0                        0    13.0000     1034.64  
883                        0                        0    30.0000     2387.62  
884                        1                        2    23.4500     1866.33  
885                        0                        0    30.0000     2387.62  
886                        0                        0     7.7500      616.80  

[887 rows x 9 columns]

**Observation** - *Converting teh Prices from USD to INR and craeting a new Column*

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Survival_Status          887 non-null    int64  
 1   Pclass                   887 non-null    int64  
 2   Name                     887 non-null    object 
 3   Gender                   887 non-null    object 
 4   Age                      887 non-null    float64
 5   Siblings/Spouses Aboard  887 non-null    int64  
 6   Parents/Children Aboard  887 non-null    int64  
 7   Fare_Paid                887 non-null    float64
 8   Prices_Inr               887 non-null    float64
dtypes: float64(3), int64(4), object(2)
memory usage: 62.5+ KB


**Observation** - *Total number of entries are 887 and Survival_status, Pclass, Siblings/Spouses Aboard,Parents/Children Aboard are interger datatype* <br>
*Age , Fare Paid are float datatype* <br>
*Name and Gender are object datatype*

In [7]:
df.describe()

Survival_Status      Pclass         Age  Siblings/Spouses Aboard  \
count       887.000000  887.000000  887.000000               887.000000   
mean          0.385569    2.305524   29.471443                 0.525366   
std           0.487004    0.836662   14.121908                 1.104669   
min           0.000000    1.000000    0.420000                 0.000000   
25%           0.000000    2.000000   20.250000                 0.000000   
50%           0.000000    3.000000   28.000000                 0.000000   
75%           1.000000    3.000000   38.000000                 1.000000   
max           1.000000    3.000000   80.000000                 8.000000   

       Parents/Children Aboard  Fare_Paid    Prices_Inr  
count               887.000000  887.00000    887.000000  
mean                  0.383315   32.30542   2571.108117  
std                   0.807466   49.78204   3962.028115  
min                   0.000000    0.00000      0.000000  
25%                   0.000000    7.92500    630.730000  
50%                   0.000000   14.45420   1150.370000  
75%                   0.000000   31.13750   2478.155000  
max                   6.000000  512.32920  40775.000000

**Observation** - *Descriptive Statistics shows the count, mean, standard deviation, min, max and quatiles of each column of the dataset which helps us to gain meaningful insights** 

In [8]:
df['Gender'].value_counts()

male      573
female    314
Name: Gender, dtype: int64

**Observation** - *The number of Males and Females are **573** and **314** respectively.*

In [9]:
df.isnull().sum()

Survival_Status            0
Pclass                     0
Name                       0
Gender                     0
Age                        0
Siblings/Spouses Aboard    0
Parents/Children Aboard    0
Fare_Paid                  0
Prices_Inr                 0
dtype: int64

**Observation** - *There are no null values in the dataset as the values are zero*

In [10]:
df.memory_usage(deep= True)

Index                        128
Survival_Status             7096
Pclass                      7096
Name                       73020
Gender                     54735
Age                         7096
Siblings/Spouses Aboard     7096
Parents/Children Aboard     7096
Fare_Paid                   7096
Prices_Inr                  7096
dtype: int64

**Observation** - *Memory Usage by the various datypes in bytes*

In [11]:
df['Survival_Status'] = df.Survival_Status.map({0:'Not Survived ', 1:'Survived'})
df.Survival_Status.value_counts()

Not Survived     545
Survived         342
Name: Survival_Status, dtype: int64

**Observation** - *The Number of Survived and not Survived People are **545** and **342** Respectively.*

In [12]:
freetravellers =df[df['Fare_Paid']==0]
print(freetravellers.head())
print("The Number of Passengers who travelled for FREE : ", len(freetravellers))

    Survival_Status  Pclass                            Name Gender   Age  \
178   Not Survived        3              Mr. Lionel Leonard   male  36.0   
261   Not Survived        1            Mr. William Harrison   male  40.0   
269        Survived       3     Mr. William Henry Tornquist   male  25.0   
275   Not Survived        2              Mr. Francis Parkes   male  21.0   
300   Not Survived        3  Mr. William Cahoone Jr Johnson   male  19.0   

     Siblings/Spouses Aboard  Parents/Children Aboard  Fare_Paid  Prices_Inr  
178                        0                        0        0.0         0.0  
261                        0                        0        0.0         0.0  
269                        0                        0        0.0         0.0  
275                        0                        0        0.0         0.0  
300                        0                        0        0.0         0.0  
The Number of Passengers who travelled for FREE :  15


**Observation** - *The numbers of Passengers who travelled for free are 15* 

In [13]:
passenger_income = []
for i in df['Prices_Inr']:
    if i > (mean(df['Prices_Inr'])):
        passenger_income.append("Above Average")
    else:
        passenger_income.append("Below Average")
df['Passenger_Income'] = passenger_income
df

Survival_Status  Pclass  \
0     Not Survived        3   
1          Survived       1   
2          Survived       3   
3          Survived       1   
4     Not Survived        3   
..              ...     ...   
882   Not Survived        2   
883        Survived       1   
884   Not Survived        3   
885        Survived       1   
886   Not Survived        3   

                                                  Name  Gender   Age  \
0                               Mr. Owen Harris Braund    male  22.0   
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  38.0   
2                                Miss. Laina Heikkinen  female  26.0   
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  female  35.0   
4                              Mr. William Henry Allen    male  35.0   
..                                                 ...     ...   ...   
882                               Rev. Juozas Montvila    male  27.0   
883                        Miss. Margaret Edith Graham  female  19.0   
884                     Miss. Catherine Helen Johnston  female   7.0   
885                               Mr. Karl Howell Behr    male  26.0   
886                                 Mr. Patrick Dooley    male  32.0   

     Siblings/Spouses Aboard  Parents/Children Aboard  Fare_Paid  Prices_Inr  \
0                          1                        0     7.2500      577.01   
1                          1                        0    71.2833     5673.26   
2                          0                        0     7.9250      630.73   
3                          1                        0    53.1000     4226.10   
4                          0                        0     8.0500      640.68   
..                       ...                      ...        ...         ...   
882                        0                        0    13.0000     1034.64   
883                        0                        0    30.0000     2387.62   
884                        1                        2    23.4500     1866.33   
885                        0                        0    30.0000     2387.62   
886                        0                        0     7.7500      616.80   

    Passenger_Income  
0      Below Average  
1      Above Average  
2      Below Average  
3      Above Average  
4      Below Average  
..               ...  
882    Below Average  
883    Below Average  
884    Below Average  
885    Below Average  
886    Below Average  

[887 rows x 10 columns]

In [14]:
df['Passenger_Income'].value_counts()

Below Average    676
Above Average    211
Name: Passenger_Income, dtype: int64

**Observation** - *The Income of Passengers were categorised based on two factors Below and Above Average*

In [15]:
table = pd.crosstab(df['Survival_Status'],df['Gender'])
print (table)

Gender           female  male
Survival_Status              
Not Survived         81   464
Survived            233   109


**Observation** - *The number of Males and  females who survived and not survived*

In [16]:
class1 = df[(df['Pclass'] == 1) & (df['Survival_Status'] == 'Survived') & (df['Gender'] == 'male')]
len(class1)

45

**Observation** - *The Male Passengers who survived in Class1 are 45*

In [17]:
class2 = df[(df['Pclass'] == 2) & (df['Survival_Status'] == 'Survived') & (df['Gender'] == 'male')]
len(class2)

17

**Observation** - *The Male Passengers who survived in Class2 are 17*

In [18]:
class3 = df[(df['Pclass'] == 3) & (df['Survival_Status'] == 'Survived') & (df['Gender'] == 'male')]
len(class3)

47

**Observation** - *The Male Passengers who survived in Class3 are 47*

In [25]:
age_category = []
for i in df['Age']:
    if i < 18:
        age_category.append("Child")
    elif i > 18 and i < 60:
        age_category.append("Adult")
    else:
        age_category.append("Senior Citizen")
df['Age_category'] = age_category
df

Survival_Status  Pclass  \
0     Not Survived        3   
1          Survived       1   
2          Survived       3   
3          Survived       1   
4     Not Survived        3   
..              ...     ...   
882   Not Survived        2   
883        Survived       1   
884   Not Survived        3   
885        Survived       1   
886   Not Survived        3   

                                                  Name  Gender   Age  \
0                               Mr. Owen Harris Braund    male  22.0   
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  38.0   
2                                Miss. Laina Heikkinen  female  26.0   
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  female  35.0   
4                              Mr. William Henry Allen    male  35.0   
..                                                 ...     ...   ...   
882                               Rev. Juozas Montvila    male  27.0   
883                        Miss. Margaret Edith Graham  female  19.0   
884                     Miss. Catherine Helen Johnston  female   7.0   
885                               Mr. Karl Howell Behr    male  26.0   
886                                 Mr. Patrick Dooley    male  32.0   

     Siblings/Spouses Aboard  Parents/Children Aboard  Fare_Paid  Prices_Inr  \
0                          1                        0     7.2500      577.01   
1                          1                        0    71.2833     5673.26   
2                          0                        0     7.9250      630.73   
3                          1                        0    53.1000     4226.10   
4                          0                        0     8.0500      640.68   
..                       ...                      ...        ...         ...   
882                        0                        0    13.0000     1034.64   
883                        0                        0    30.0000     2387.62   
884                        1                        2    23.4500     1866.33   
885                        0                        0    30.0000     2387.62   
886                        0                        0     7.7500      616.80   

    Passenger_Income Age_category  
0      Below Average        Adult  
1      Above Average        Adult  
2      Below Average        Adult  
3      Above Average        Adult  
4      Below Average        Adult  
..               ...          ...  
882    Below Average        Adult  
883    Below Average        Adult  
884    Below Average        Child  
885    Below Average        Adult  
886    Below Average        Adult  

[887 rows x 11 columns]

In [26]:
df['Age_category'].value_counts()

Adult             690
Child             130
Senior Citizen     67
Name: Age_category, dtype: int64

**Observation** - *The People are categorised based on Adult,Child and Senior Citizen respectively.*

In [47]:
df = df.drop('Fare_Paid' ,axis='columns')
df

Survival_Status  Pclass  \
0     Not Survived        3   
1          Survived       1   
2          Survived       3   
3          Survived       1   
4     Not Survived        3   
..              ...     ...   
882   Not Survived        2   
883        Survived       1   
884   Not Survived        3   
885        Survived       1   
886   Not Survived        3   

                                                  Name  Gender   Age  \
0                               Mr. Owen Harris Braund    male  22.0   
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  38.0   
2                                Miss. Laina Heikkinen  female  26.0   
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  female  35.0   
4                              Mr. William Henry Allen    male  35.0   
..                                                 ...     ...   ...   
882                               Rev. Juozas Montvila    male  27.0   
883                        Miss. Margaret Edith Graham  female  19.0   
884                     Miss. Catherine Helen Johnston  female   7.0   
885                               Mr. Karl Howell Behr    male  26.0   
886                                 Mr. Patrick Dooley    male  32.0   

     Siblings/Spouses Aboard  Parents/Children Aboard  Prices_Inr  \
0                          1                        0      577.01   
1                          1                        0     5673.26   
2                          0                        0      630.73   
3                          1                        0     4226.10   
4                          0                        0      640.68   
..                       ...                      ...         ...   
882                        0                        0     1034.64   
883                        0                        0     2387.62   
884                        1                        2     1866.33   
885                        0                        0     2387.62   
886                        0                        0      616.80   

    Passenger_Income Age_category Married_Status  
0      Below Average        Adult      Unmarried  
1      Above Average        Adult      Unmarried  
2      Below Average        Adult      Unmarried  
3      Above Average        Adult      Unmarried  
4      Below Average        Adult      Unmarried  
..               ...          ...            ...  
882    Below Average        Adult      Unmarried  
883    Below Average        Adult      Unmarried  
884    Below Average        Child      Unmarried  
885    Below Average        Adult      Unmarried  
886    Below Average        Adult      Unmarried  

[887 rows x 11 columns]

**Observation** - *Droped the Fare_Paid column from the dataset*

In [48]:
pclass_map = {1: 'Upper_class', 2: 'Middle_class', 3: 'Lower_class'}
df['Pclass'] = df['Pclass'].map(pclass_map)
table = pd.crosstab(df['Survival_Status'],df['Pclass'])
print (table)

Pclass           Lower_class  Middle_class  Upper_class
Survival_Status                                        
Not Survived             368            97           80
Survived                 119            87          136


**Observation** - *The number of Lower_Class ,Middle_class & Upper_class Survived and Not Survived , i.e. ,categorisation based upon classes*

In [49]:
#The iterrows() method generates an iterator object of the DataFrame, allowing us to iterate each row in the DataFrame.
married = []
for index, row in df.iterrows():
    if row["Name"] == ("Mrs." ):
        married.append("Married")
    elif row["Name"] == ("Mr."):
        married.append("Married")
    else :
        married.append("Unmarried")
df["Married_Status"] = married
df

Survival_Status        Pclass  \
0     Not Survived    Lower_class   
1          Survived   Upper_class   
2          Survived   Lower_class   
3          Survived   Upper_class   
4     Not Survived    Lower_class   
..              ...           ...   
882   Not Survived   Middle_class   
883        Survived   Upper_class   
884   Not Survived    Lower_class   
885        Survived   Upper_class   
886   Not Survived    Lower_class   

                                                  Name  Gender   Age  \
0                               Mr. Owen Harris Braund    male  22.0   
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  female  38.0   
2                                Miss. Laina Heikkinen  female  26.0   
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  female  35.0   
4                              Mr. William Henry Allen    male  35.0   
..                                                 ...     ...   ...   
882                               Rev. Juozas Montvila    male  27.0   
883                        Miss. Margaret Edith Graham  female  19.0   
884                     Miss. Catherine Helen Johnston  female   7.0   
885                               Mr. Karl Howell Behr    male  26.0   
886                                 Mr. Patrick Dooley    male  32.0   

     Siblings/Spouses Aboard  Parents/Children Aboard  Prices_Inr  \
0                          1                        0      577.01   
1                          1                        0     5673.26   
2                          0                        0      630.73   
3                          1                        0     4226.10   
4                          0                        0      640.68   
..                       ...                      ...         ...   
882                        0                        0     1034.64   
883                        0                        0     2387.62   
884                        1                        2     1866.33   
885                        0                        0     2387.62   
886                        0                        0      616.80   

    Passenger_Income Age_category Married_Status  
0      Below Average        Adult      Unmarried  
1      Above Average        Adult      Unmarried  
2      Below Average        Adult      Unmarried  
3      Above Average        Adult      Unmarried  
4      Below Average        Adult      Unmarried  
..               ...          ...            ...  
882    Below Average        Adult      Unmarried  
883    Below Average        Adult      Unmarried  
884    Below Average        Child      Unmarried  
885    Below Average        Adult      Unmarried  
886    Below Average        Adult      Unmarried  

[887 rows x 11 columns]

**Observation** - *The number of Married and unmarried Peoples*